<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => '飲食業界就活はフーズラボエージェント フォーム の送信',
	'heading' => '新規フォームの送信',
	'success_redirect' => '../phone/thanks.html',
	'resources' => array(
		'checkbox_checked' => 'チェック済み',
		'checkbox_unchecked' => '未チェック',
		'submitted_from' => 'Web サイトから送信されたフォーム : %s',
		'submitted_by' => '訪問者の IP アドレス : %s',
		'too_many_submissions' => '最近、この IP からの送信回数が多すぎます',
		'failed_to_send_email' => '電子メールの送信に失敗しました',
		'invalid_reCAPTCHA_private_key' => '無効な reCAPTCHA プライベートキーです。',
		'invalid_reCAPTCHA2_private_key' => '無効な reCAPTCHA 2.0 プライベートキーです。',
		'invalid_reCAPTCHA2_server_response' => '無効な reCAPTCHA 2.0 サーバー応答です。',
		'invalid_field_type' => '不明なフィールドの種類「%s」です。',
		'invalid_form_config' => 'フィールド「%s」には無効な設定が含まれています。',
		'unknown_method' => '不明なサーバー要求メソッド'
	),
	'email' => array(
		'from' => 'new-grads@cuolega.co.jp',
		'to' => 'new-grads@cuolega.co.jp,info@cuolega.co.jp'
	),
	'fields' => array(
		'custom_U4134' => array(
			'order' => 1,
			'type' => 'string',
			'label' => '名前',
			'required' => true,
			'errors' => array(
				'required' => 'フィールド「名前」が必要です。'
			)
		),
		'custom_U4121' => array(
			'order' => 2,
			'type' => 'string',
			'label' => '電話番号',
			'required' => true,
			'errors' => array(
				'required' => 'フィールド「電話番号」が必要です。'
			)
		),
		'custom_U4130' => array(
			'order' => 4,
			'type' => 'string',
			'label' => '学校名',
			'required' => true,
			'errors' => array(
				'required' => 'フィールド「学校名」が必要です。'
			)
		),
		'custom_U4125' => array(
			'order' => 5,
			'type' => 'string',
			'label' => '都道府県',
			'required' => true,
			'errors' => array(
				'required' => 'フィールド「都道府県」が必要です。'
			)
		),
		'custom_U4154' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'ご希望の業態',
			'required' => true,
			'errors' => array(
				'required' => 'フィールド「ご希望の業態」が必要です。'
			)
		),
		'custom_U8231' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'メールアドレス',
			'required' => true,
			'errors' => array(
				'required' => 'フィールド「メールアドレス」が必要です。'
			)
		),
		'custom_U4138' => array(
			'order' => 6,
			'type' => 'checkboxgroup',
			'label' => 'ご希望勤務先',
			'required' => true,
			'optionItems' => array(
				'東京都（23区内）',
				'神奈川',
				'東京都（23区外）'
			),
			'errors' => array(
				'required' => 'フィールド「ご希望勤務先」が必要です。',
				'format' => 'フィールド「ご希望勤務先」には無効な値が含まれています。'
			)
		)
	)
);

process_form($form);
?>
